Trangsuc/Controllers/cartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trangsuc.Models;
using System.Text.RegularExpressions;
using Trangsuc.ServiceReferenceTonkho;
using System.Net.Mail;
using System.Net;
namespace Trangsuc.Controllers
{
    public class cartController : Controller
    {
        ServiceReferenceSanpham.ServiceSanphamClient db = new ServiceReferenceSanpham.ServiceSanphamClient();
        ServiceReferenceNguoidung.ServiceNguoidungClient dbnguoidung = new ServiceReferenceNguoidung.ServiceNguoidungClient();
        ServiceTonkhoClient dbtonkho = new ServiceTonkhoClient();
        public bool IsNumber(string pText)
        {
            Regex regex = new Regex(@"^[-+]?[0-9]*\.?[0-9]+$");
            return regex.IsMatch(pText);
        }
        public RedirectToRouteResult giohangthem(string masanpham, string soluong = "1")
        {
            Tonkho_DTO tk = dbtonkho.Find(masanpham);
            if (tk.Soluong > 0)
            {
                if (IsNumber(soluong))
                {
                    if (int.Parse(soluong) <= tk.Soluong)
                    {
                        if (int.Parse(soluong) < 1)
                        {
                            var item = db.Find(masanpham);
                            GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, 1);
                        }
                        else
                        {
                            var item = db.Find(masanpham);
                            GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, int.Parse(soluong));
                        }
                    }
                    else
                    {
                        var item = db.Find(masanpham);
                        GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, tk.Soluong);
                    }
                }
                else
                {
                    var item = db.Find(masanpham);
                    GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, 1);
                }
                return RedirectToAction("Index");
            }
            else {
                return RedirectToAction("Index","Home");
            }
           
        }

        public RedirectToRouteResult giohangxoa(string masanpham)
        {
            GetCart().RemoveLine(masanpham);
            return RedirectToAction("Index");
        }

       
        public RedirectToRouteResult capnhatsoluong(string masanpham, string soluong)
        {
            Tonkho_DTO tk = dbtonkho.Find(masanpham);
            if (IsNumber(soluong))
            {            
                    if (int.Parse(soluong) <= tk.Soluong)
                    {
                        if (int.Parse(soluong) < 1)
                            GetCart().capnhatsoluong(masanpham, 1);
                        else
                            GetCart().capnhatsoluong(masanpham, int.Parse(soluong));
                    }
                    else
                    {  
                        GetCart().capnhatsoluong(masanpham, tk.Soluong); 
                    }
               
            }
            else
            {            
                    GetCart().capnhatsoluong(masanpham, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToRouteResult xoahet()
        {
            GetCart().Clear();
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult menugiohang()
        {
            return PartialView(GetCart());
        }
        //Gán session["Cart"] cho giỏ hàng
        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }

        [ChildActionOnly]
        public ActionResult footergiohang()
        {
            return PartialView();
        }


  
        public void ngaythangnam()
        {
            int nam = DateTime.Now.Year;
            List<SelectListItem> ngayList = new List<SelectListItem>();
            List<SelectListItem> thangList = new List<SelectListItem>();
            List<SelectListItem> namList = new List<SelectListItem>();
            for (int i = 1; i <= 31; i++)
            {
                string j = i.ToString();
                ngayList.Add(new SelectListItem { Text = j, Value = j });
            }
            for (int i = 1; i <= 12; i++)
            {
                string j = i.ToString();
                thangList.Add(new SelectListItem { Text = j, Value = j });
            }
            for (int i = nam; i <= nam + 1; i++)
            {
                string j = i.ToString();
                namList.Add(new SelectListItem { Text = j, Value = j });
            }
            ViewBag.ngay = ngayList;
            ViewBag.thang = thangList;
            ViewBag.nam = namList;
        }
        public ActionResult thanhtoangiohang()
        {
            if (GetCart().Lines.Count() > 0)
            {              
                    string username = (string)Session["User"];
                    var tt = GetCart().thongtinkh(username);
                        ViewBag.username = tt.Hoten;
                        ViewBag.sdt = tt.Sdt;
                        ViewBag.email = tt.Mail;
                        ViewBag.diachi = tt.Diachi;
                        ngaythangnam();
                        return View(GetCart());
            }
            return RedirectToAction("index");
        }

        //thanh toán giỏ hàng rồi gửi mail chi tiết đơn hàng cho khách hàng
        [HttpPost]
        public ActionResult thanhtoangiohang(FormCollection f)
        {

            Cart cart = GetCart();
            string name = Session["User"].ToString();
            ServiceReferenceNguoidung.Nguoidung_DTO user = new ServiceReferenceNguoidung.Nguoidung_DTO();
            user = dbnguoidung.GetNguoidungByUsername(name);

            string Email = user.Mail.Trim();
            string chuoi = " GIỎ HÀNG CỦA QUÝ KHÁCH\n";

            foreach (var item in cart.Lines)
            {
                chuoi += "Mã SP: " + item.masp + "\tTên SP: " + item.tensp + "\tSố lượng: " + item.Quantity + "\tGiá SP: " + item.giasanpham + "\n";
            }
            chuoi += "Tổng tiền:" + cart.tongtien() + "VND\n";
            chuoi += "Cám ơn quý khách đã chọn sản phẩm của công ty. Chúng tôi sẽ liên hệ sớm với quý khách.";
            MailMessage msg = new MailMessage();
            msg.From = new MailAddress("trangsucviet05@gmail.com");
            msg.To.Add(Email);
            msg.Subject = "Trangsucviet: GIỎ HÀNG CỦA QUÝ KHÁCH TẠI Trangsucviet.com.vn";
            msg.Body = chuoi;

            //cấu hình mail smtp
            #region SMTP
            SmtpClient smtp = new SmtpClient();
            smtp.Credentials = new NetworkCredential("trangsucviet05@gmail.com", "seminarnhom05");
            smtp.Port = 587;
            smtp.Host = "smtp.gmail.com";
            smtp.EnableSsl = true;
            smtp.Send(msg);
            #endregion

            int ngay = int.Parse(f["ngay"]);
            int thang = int.Parse(f["thang"]);
            int nam = int.Parse(f["nam"]);              
            DateTime ngaygiaohang = new DateTime(nam, thang, ngay);
               
            //Lưu hóa đơn hàng xuống csdl
            GetCart().save((string)Session["User"], f["diachi"], ngaygiaohang, f["sdt"]);

            //xóa danh sách sản phẩm có trong giỏ hàng
            GetCart().Clear();
            return RedirectToAction("Index", "home");
        }

     
        public ViewResult Index()
        {
            return View(GetCart());
        }
    }
}

Trangsuc/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trangsuc.ServiceReferenceNguoidung;
using Trangsuc.Models;
using System.Web.Security;
using System.Web.Routing;
using System.Net.Mail;
using System.Net;
using System.Web.Helpers;

namespace Trangsuc.Controllers
{
    public class userController : Controller
    {
        //
        // GET: /user/
        ServiceNguoidungClient dbnguoidung = new ServiceNguoidungClient();
        public List<Nguoidung_DTO> danhsachnguoidung = new List<Nguoidung_DTO>();
        public List<Nguoidung_DTO> danhsachnguoidungan = new List<Nguoidung_DTO>();

        public void dsnguoidung()
        {
            danhsachnguoidung.Clear();
            danhsachnguoidung = dbnguoidung.GetAllNguoidung().Where(x => x.Useran == false).ToList();
        }

        public bool kiemtranguoidung(Nguoidung_DTO nd)
        {
            Nguoidung_DTO kt = dbnguoidung.GetNguoidungByUsername(nd.Username);
            if (kt != null)
            {
                return false;
            }
            else return true;
        }

        public bool kiemtradangnhap(Nguoidung_DTO nd)
        {
            
            dsnguoidung();
            var _nd = danhsachnguoidung.SingleOrDefault(x=>x.Username.Equals(nd.Username));
            if (_nd != null)
            {
                var passmahoa =_nd.Pass;
                //kiem tra pass
                var check = Crypto.VerifyHashedPassword(passmahoa, nd.Pass);
                return check;
            }
            else return false;
        }

        public void dsnguoidungan()
        {
            danhsachnguoidungan.Clear();
            danhsachnguoidungan = dbnguoidung.GetAllNguoidung().Where(x => x.Useran == true).ToList();
        }
        public bool kiemtradangnhapan(Nguoidung_DTO nd)
        {
           
            dsnguoidungan();
            var _nd = danhsachnguoidungan.SingleOrDefault(x => x.Username.Equals(nd.Username));
            if (_nd != null)
            {
                var passmahoa = _nd.Pass;

                var check = Crypto.VerifyHashedPassword(passmahoa, nd.Pass);
                return check;
            }
            else return false;
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(dangnhap model, string returnUrl)
        {
            
                Nguoidung_DTO nd = new Nguoidung_DTO();
                nd.Username = model.username;
                nd.Pass = model.password;
                bool _remember = model.remember;
                bool userValid = kiemtradangnhap(nd);
                    if (userValid)
                    {
                        Session["User"] = nd.Username;
                        Session["Admin"] = null;
                        FormsAuthentication.SetAuthCookie(nd.Username,_remember);
                        if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                            && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home");
                        }        
                    }    
                    else
                    {
                        bool useranValid = kiemtradangnhapan(nd);
                        // nếu người dùng ẩn thì không cho đăng nhập
                        if (useranValid)
                        {
                            ModelState.AddModelError("", "Tài khoản đã bị khóa. Mọi thắc mắc vui lòng liên hệ ban quản trị.");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Sai tên hoặc mật khẩu đăng nhập");
                        }
                        return View();
                    }    
           
        }

        public ActionResult DangXuat()
        {
            Session["User"] = null;
            Session["Cart"] = null;
            return RedirectToAction("Index", "Home");
        }

        bool kiemtranamnhuan(int nam)
        {
            if (nam % 4 == 0 && nam % 100 != 0)
                return true;
            return false;
        }

        bool kiemtrangaysinh(int ngay, int thang, int nam)
        {
            int ngaynhuan = 0;
            if (thang == 2)
            {
                if (kiemtranamnhuan(nam))
                    ngaynhuan = 29;
                else
                    ngaynhuan = 28;
                if (ngay > ngaynhuan)
                {
                    return false;
                }
            }
            else
                if (thang == 4 || thang == 6 || thang == 9 || thang == 11)
                    if (ngay > 30)
                        return false;
            return true;
        }

        public void ngaythangnam()
        {
            int namtu = DateTime.Now.Year - 65;
            int namden = DateTime.Now.Year - 16;
            List<SelectListItem> ngayList = new List<SelectListItem>();
            List<SelectListItem> thangList = new List<SelectListItem>();
            List<SelectListItem> namList = new List<SelectListItem>();
            for (int i = 1; i <= 31; i++)
            {
                string j = i.ToString();
                ngayList.Add(new SelectListItem { Text = j, Value = j });
            }
            for (int i = 1; i <= 12; i++)
            {
                string j = i.ToString();
                thangList.Add(new SelectListItem { Text = j, Value = j });
            }
            for (int i = namtu; i <= namden; i++)
            {
                string j = i.ToString();
                namList.Add(new SelectListItem { Text = j, Value = j });
            }
            ViewBag.ngay = ngayList;
            ViewBag.thang = thangList;
            ViewBag.nam = namList;
        }

        [HttpGet]
        public ActionResult DangKy()
        {
            ngaythangnam();
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(dangky model, FormCollection form)
        {
            int gt = int.Parse(form["gioitinh"].ToString());
            int ngay = int.Parse(form["ngay"]);
            int thang = int.Parse(form["thang"]);
            int nam = int.Parse(form["nam"]);
            if (kiemtrangaysinh(ngay, thang, nam))
            {
                DateTime ns = new DateTime(nam, thang, ngay);
                try
                {
                    //ma hoa password
                    var passmahoa = Crypto.HashPassword(model.password);
                    Nguoidung_DTO nd = new Nguoidung_DTO();
                    nd.Username = model.username;
                    nd.Pass = passmahoa;
                    nd.Hoten = model.hoten;
                    nd.Ngaysinh = ns;
                    nd.Sdt = model.sdt;
                    nd.Diachi = model.diachi;
                    nd.Mail = model.email;
                    nd.Gioitinh =  gt;
                    if (kiemtranguoidung(nd))
                    {
                       if(dbnguoidung.Insert(nd))
                       {
                            ViewBag.thanhcong = "Đăng ký thành công!";
                        }
                       else
                        {
                             
                            ViewBag.thanhcong = null;
                            ViewBag.thatbai = "Dang ky that bai";
                        }                       
                    }
                    else
                    {                      
                        ViewBag.thanhcong = null;
                        ViewBag.thatbai = "Tên đăng nhập đã tồn tại!";
                    }
                    ngaythangnam();
                    return View();
                }
                catch
                {
                    ngaythangnam();
                    ViewBag.thatbai = "Dang ky that bai tai catch";
                    return View();
                }
            }
            else
            {
                ngaythangnam();
                ViewBag.loi = "Ngày sinh không hợp lệ!";
                return View();
            }
        }


        public ActionResult SuaThongTin()
        {
           
                    string username = Session["User"].ToString();
                    Nguoidung_DTO nd = dbnguoidung.GetNguoidungByUsername(username);                  
                    suathongtin _sua = new suathongtin();
                    _sua.username = nd.Username;
                    _sua.hoten = nd.Hoten;
                    _sua.sdt = nd.Sdt;
                    _sua.email = nd.Mail;
                    _sua.password = null;
                    _sua.passwordcu = null;
                    _sua.xacnhanmatkhau = null;
                    return View(_sua);
        }

        [HttpPost]
        public ActionResult SuaThongTin(suathongtin nd_sua)
        {
            
                    Nguoidung_DTO _nd = new Nguoidung_DTO();
                    _nd.Username = nd_sua.username;
                    _nd.Pass = nd_sua.passwordcu;
                    bool userValid = kiemtradangnhap(_nd);
                    if (userValid)
                    {
                        Nguoidung_DTO _nd_sua = dbnguoidung.GetNguoidungByUsername(_nd.Username);                  
                                _nd_sua.Sdt = nd_sua.sdt;
                                _nd_sua.Mail = nd_sua.email;
                                _nd_sua.Pass = Crypto.HashPassword(nd_sua.password);
                                dbnguoidung.Update(_nd_sua);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {

Trangsuc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
     <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/script.js")" type="text/javascript"></script>
</head>
<body>
    <div class="container">
        <!--dau trang-->
        <a name="top"><div class="banner"></div></a>
        <div class="menu">
            <div class="button">@Html.ActionLink("TRANG CHỦ", "Index", "Home")</div>
            <div class="menu-space"></div>
            <div class="button">@Html.ActionLink("GIỚI THIỆU", "GioiThieu", "Home")</div>
            <div class="menu-space"></div>
            <div class="button">@Html.ActionLink("TIN TỨC", "TinTuc", "Home")</div>
            <div class="menu-space"></div>
            <div class="button">@Html.ActionLink("CỬA HÀNG", "CuaHang", "Home")</div>
            <div class="menu-space"></div>
            <div class="button">@Html.ActionLink("TUYỂN DỤNG", "TuyenDung", "Home")</div>
	        <div class="time"> <script>time()</script></div>
            <div class="clear"></div>
        </div>
        <!--giua  trang-->
        <div class="main">
            <!--cot trai-->
            <div class="columnleft">
                <div class="header-column">DANH MỤC SẢN PHẨM</div>
                <div class="noidungcanhtrai">
  	  	            <div style="margin-top:3px">
                        <div class="sidebarmenu">
			                @{Html.RenderAction("Menu", "loaisanpham");}
         	            </div>
                    </div>
                </div>
                <div class="header-column">SẢN PHẨM NỔI BẬT</div>
                    @{Html.RenderAction("spbanchay", "sanpham");}
            </div>
            <!--cot giua trong-->
            <section>
                 @RenderBody()
            </section> 
            <!--cot phai-->
            <div class="columnright">
                <div class="header-column">ĐĂNG NHẬP</div>
                <div class="noidungdangnhap">
                    
                     @if (Session["User"]!=null)
                        {
                            Session["Admin"] = null;
                            <div>
                                <div style="margin-top:5px">Xin chào <strong>@Session["User"]</strong></div>
                                <div><img src="@Url.Content("~/Image/hinhdangnhap.png")" style="margin-left:60px" width="55" height="55"/></div>
                                <div style="margin-top:5px"><a href="/user/lichsumuahang">Lịch sử giao dịch</a></div>
                                <div style="margin-top:5px"><a href="/user/suathongtin">Sửa thông tin</a></div>
                                <div style="margin-top:5px">@Html.ActionLink("Đăng xuất", "DangXuat", "user")</div>
                            </div>
                        }
                        else
                        {
                            <div>
                                @using (Html.BeginForm("DangNhap", "user"))
                                { 
                                    <form name="dangnhap" method="post">
                                                <table>
                                                    <tr>
                                                        <td align="left">Tên truy cập</td>
                                                        <td><input type="text" name="username" id="username" size="15" maxlength="35" /><br></td>

                                                    </tr>
                                                    <tr>
                                                        <td align="left">Mật khẩu</td>
                                                        <td><input type="password" name="password" id="password" size="15" value="" ><br></td>
                                                    </tr>
                                                    <tr>
                                                        <td></td>
                                                        <td align="left"><input id="remember" class="checkbox" type="checkbox" value="true" name="remember">Ghi nhớ</td>
                                                    </tr>
                                                    <tr>
                                                        <td></td>
                                                        <td align="left"><input type="submit" style="text-align:center" value="Đăng nhập"></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2">
            	                                        <div>@Html.ActionLink("Đăng ký thành viên", "DangKy", "user")</div>
                                                        </td>
                                                    </tr>
                                                     <tr>
                                                        <td colspan="2">
            	                                        <div>@Html.ActionLink("Quên mật khẩu", "Quenmatkhau", "user")</div>
                                                        </td>
                                                    </tr>
                                                </table>   
        	                                 </form>
                                }  
                            </div>
                        }

                </div>
                @{Html.RenderAction("menugiohang", "cart");}
               
                <div class=" header-column">HỖ TRỢ TRỰC TUYẾN</div>
                <div class="noidungcanhgiua">
                    <div>(Huỳnh Bá Đạt)</div>
                    <div align="center"><a href="ymsgr:anhmaiyeuem200"><img src="@Url.Content("~/Image/online.gif")"/></a></div>
                    <div>----------------------</div>
                    <div>(Phạm Hoàng Hiệp)</div>
                    <div align="center"><a href="ymsgr:phamhoang_tg5303"><img src="@Url.Content("~/Image/offline.gif")"/></a></div>
    	        </div>
                <div class="noidungcanhgiua2" style="margin-bottom: 5px">
                <img height="229px" src="@Url.Content("~/Image/logofix.png")"/>
                </div>
            </div><div class="clear"></div>
        </div>
        <!--cuoi trang-->
        
  	    <div class="footer">
  	        © Copyright 2014 <b>DEW</b>, All rights reserved.<br />
  	    </div>
  	    <div style="height:3px"></div>
           
    </div>        
</body>
</html>