Trangsuc/Areas/Admin/Controllers/adminpagingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Trangsuc.Areas.Admin.Controllers
{
    public class adminpagingController : Controller
    {
        //
        // GET: /Admin/paging/

        [ChildActionOnly]
        public ActionResult Index(int page = 1, string currentpage = null, int totalpages = 1)
        {
            ViewBag.currentpage = currentpage;
            ViewBag.Page = page;
            ViewBag.TotalPages = totalpages;
            return PartialView();
        }
    }
}

Trangsuc/Areas/Admin/Controllers/quanlysanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trangsuc.Models;
using System.IO;
using Trangsuc.ServiceReferenceSanpham;
namespace Trangsuc.Areas.Admin.Controllers
{
    public class quanlysanphamController : Controller
    {
      
                public List<Sanpham_DTO> danhsachtatcasanpham = new List<Sanpham_DTO>();
                public List<Sanpham_DTO> danhsachsanpham = new List<Sanpham_DTO>();
                public List<Sanpham_DTO> danhsachsanphaman = new List<Sanpham_DTO>();
                ServiceSanphamClient dbsanpham = new ServiceSanphamClient();
                 int pagesize = 6;

                public void dstatcasanpham()
                {
                    danhsachtatcasanpham.Clear();
                    danhsachtatcasanpham = dbsanpham.GetAllSp().ToList();
                }

                List<Loaisanpham_DTO> danhsachloaisanpham = new List<Loaisanpham_DTO>();
                public void dsloaisanpham()
                {
                    danhsachloaisanpham.Clear();
                    danhsachloaisanpham = dbsanpham.GetAllLoaiSp().ToList();
                }
                [ChildActionOnly]
                public ActionResult Menu()
                {
                    dsloaisanpham();
                    return PartialView(danhsachloaisanpham);
                }

                public void ds_sanpham()
                {
                    dstatcasanpham();
                    danhsachsanpham = (from sp in danhsachtatcasanpham where sp.Sanphammoi == 1 select sp).ToList();
                }

                public void ds_sanpham_an()
                {
                    dstatcasanpham();
                    danhsachsanphaman = (from sp in danhsachtatcasanpham where sp.Sanphammoi == 0 select sp).ToList();
                }

                public ActionResult Index(int page=1)
                {
                    ds_sanpham();
                    ViewBag.TotalPages = Math.Ceiling((double)danhsachsanpham.Count / pagesize);
                    return View(danhsachsanpham.Skip((page - 1) * pagesize).Take(pagesize));
                }

                public ActionResult sanphaman(int page = 1)
                {
                    ds_sanpham_an();
                    ViewBag.TotalPages = Math.Ceiling((double)danhsachsanphaman.Count / pagesize);
                    return View(danhsachsanphaman.Skip((page - 1) * pagesize).Take(pagesize));
                }

                public ActionResult ketquatimkiem(int page=1)
                {
                    ds_sanpham();
                    string id = Request.QueryString["chuoitk"];
                    id = id.ToLower();
                    List<Sanpham_DTO> kqtimkiem = new List<Sanpham_DTO>();
                    foreach (var item in danhsachsanpham)
                    {
                        if (item.Tensanpham.ToLower().Contains(id) || item.Masanpham.Trim().ToLower().Contains(id))
                            kqtimkiem.Add(item);
                    }
                    ViewBag.Chuoi = id;
                    ViewBag.KhongTimThay = "Không tìm thấy";
                    ViewBag.TotalPages = Math.Ceiling((double)kqtimkiem.Count / pagesize);
                    return View(kqtimkiem.Skip((page - 1) * pagesize).Take(pagesize));
                }

                public ActionResult ketquatimkiemdanhmuc(string id, int page = 1)
                {
                    string chuoitk = Request.QueryString["chuoitk"];
                    chuoitk = chuoitk.ToLower();
                    List<Sanpham_DTO> kqtimkiem = new List<Sanpham_DTO>();
                    List<Sanpham_DTO> lstspcungloai = dbsanpham.GetSpCungLoai(id).Where(x=> x.Sanphammoi ==1).ToList();
                    foreach (Sanpham_DTO item in lstspcungloai)
                    {
                        if (item.Tensanpham.ToLower().Contains(chuoitk) || item.Masanpham.Trim().ToLower().Contains(chuoitk))
                        {
                            kqtimkiem.Add(item);
                        }
                    }
                    ViewBag.tenloai = lstspcungloai.First().Loai.Tenloai;
                    ViewBag.Chuoi = chuoitk;
                    ViewBag.KhongTimThay = "Không tìm thấy";
                    ViewBag.TotalPages = Math.Ceiling((double)kqtimkiem.Count / pagesize);
                    return View(kqtimkiem.Skip((page - 1) * pagesize).Take(pagesize));
                }

                //
                // GET: /Admin/quanlysanpham/Details/5

                public ActionResult danhmuc(string id, int page=1)
                {
                    List<Sanpham_DTO> dsspcungloai = dbsanpham.GetSpCungLoai(id).Where(x=> x.Sanphammoi == 1).ToList();
                    ViewBag.tenloai = dsspcungloai.First().Loai.Tenloai;
                    ViewBag.TotalPages = Math.Ceiling((double)dsspcungloai.Count / pagesize);
                    ViewBag.maloai = id;
                    return View(dsspcungloai.Skip((page - 1) * pagesize).Take(pagesize));

                }

                //
                // GET: /Admin/quanlysanpham/Create

                private bool kiemtrasanpham(sanphamthem sp)
                {
                    if(dbsanpham.Find(sp.masanpham)!= null)
                            return false;
                    return true;
                }

               
                public void loaisanpham()
                {
                    List<SelectListItem> loaispList = new List<SelectListItem>();
                    dsloaisanpham();
                    foreach (Loaisanpham_DTO lsp in danhsachloaisanpham)
                    {
                        string maloai = lsp.Maloai.ToString();
                        string tenloai = lsp.Tenloai.ToString();
                        loaispList.Add(new SelectListItem { Text = tenloai, Value = maloai });
                    }
                    ViewBag.loaispList = loaispList;
                }

                public string laytenloai(string maloai)
                {
                    string tenloai = null; 
                    if (maloai.Contains("BT"))
                    {
                        tenloai = "bongtai";
                    }
                    else if (maloai.Contains("DC"))
                    {
                        tenloai ="daychuyen";
                    }
                    else if (maloai.Contains("L"))
                    {
                        tenloai ="lac";
                    }
                    else if (maloai.Contains("M"))
                    {
                        tenloai ="matday";
                    }
                    else if (maloai.Contains("N"))
                    {
                        tenloai ="nhan";
                    }
                    else tenloai ="vong";
                    return tenloai;
                }

                
                [HttpGet]
                public ActionResult themsanpham()
                {
                    loaisanpham();
                    return View();
                }

              
                //
                // POST: /Admin/quanlysanpham/Create

                [HttpPost]
                public ActionResult themsanpham(HttpPostedFileBase file,sanphamthem sanphammoi, FormCollection form)
                {
                    if (ModelState.IsValid)
                    {
                        sanphammoi.maloai = form["loai"];
                        if (kiemtrasanpham(sanphammoi))
                        {
                            if (file != null && file.ContentLength > 0)
                            {
                                Sanpham_DTO sp = new Sanpham_DTO();
                                sp.Masanpham = sanphammoi.masanpham;
                                sp.Tensanpham = sanphammoi.tensanpham;
                                sp.Giasanpham = sanphammoi.giasanpham;
                                sp.Chatlieu = sanphammoi.chatlieu;
                                sp.Loai = dbsanpham.GetLoaisp(sanphammoi.maloai);
                                string hinhanh = file.FileName.ToString();
                                string tenloai = laytenloai(sanphammoi.maloai);
                                string url = "image/" + tenloai + "/" + hinhanh;
                                //extract only the fielname
                                var fileName = Path.GetFileName(file.FileName);
                                // store the file inside ~/App_Data/uploads folder
                                var path = Path.Combine(Server.MapPath("~/image/" + tenloai + "/"), fileName);
                                file.SaveAs(path);
                                sp.Hinhanh = url;
                                dbsanpham.Insert(sp);
                                return RedirectToAction("Index", "quanlysanpham");
                            }
                            else
                            {
                                loaisanpham();
                                ViewBag.hinhanh = "Chưa chọn hình ảnh";
                                return View();
                            }
                        }
                        else
                        {
                            loaisanpham();
                            ViewBag.thatbai = "Trùng mã sản phẩm";
                            return View();
                        }
                    }
                    loaisanpham();
                    return View(sanphammoi);
                }
        
 
                public ActionResult suathongtin()
                {
                    string id = Request.QueryString["masp"];
                    Sanpham_DTO sanphamsua = dbsanpham.Find(id);
                    sanphamsua sp = new sanphamsua();
                    sp.masanpham = sanphamsua.Masanpham;
                    sp.tensanpham = sanphamsua.Tensanpham;
                    sp.giasanpham = sanphamsua.Giasanpham;

Trangsuc/Areas/Admin/Views/quanlysanpham/Index.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>
@if (Session["Admin"] != null)
{
    {
        Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
    }
    <script type="text/javascript" src="@Url.Content("~/Scripts/script.js")"></script>
    <div class="headercolumn">QUẢN LÝ SẢN PHẨM</div>
    <div class="noidungright">
    <div style="width:990px">
    <div style="width:990px">
        <table>
            <tr>
                <td style="width:490px; text-align:left">
                    <div class="tieude2">
                        <a href="/admin/quanlysanpham/themsanpham" style="text-decoration:none">
                            <img src="@Url.Content("~/images/them.png")" width="10px" height="10px"/> Thêm sản phẩm mới
                        </a>
                    </div>
                </td>
                <td style="width:500px; text-align:right">
                    <div style="margin:5px; width:500px; float:right">
                        <form action="/admin/quanlysanpham/ketquatimkiem" method="get"> 
                            <input style="width:250px; height: 17px" id="coban" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="Nhập tên sản phẩm..." name="chuoitk" autocomplete="off" size="36" />
                            <input style="width:40px; height: 26px" type="submit" name="tkcoban" value="Tìm" />
                        </form>
                    </div> 
                </td>
            </tr>
        </table>
    </div>
    <div style="width:990px"><div class="tieude"><center>Danh sách sản phẩm</center></div></div>
        
        <table class="tablenguoidung">
            <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Chất liệu</th>
                <th>Giá (VNĐ)</th>
                <th style="width:80px">Hình ảnh</th>
                <th>Loại</th>
                <th colspan="2">
                    <a href="/admin/quanlysanpham/themsanpham" style="text-decoration:none">
                            <img src="@Url.Content("~/images/them.png")" width="20px" height="20px"/>
                            <div class="themmoi">Thêm mới</div>
                    </a>
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Masanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Tensanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Chatlieu)</td>
                    @{
                    string formatgia = item.Giasanpham.ToString("c");
                    formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
                        }
                    <td>@formatgia</td>
                    <td><img src="@Url.Content("~/" + @Html.DisplayFor(modelItem => item.Hinhanh))" width="75px" height="75px"/></td>
                    <td>@Html.DisplayFor(modelItem => item.Loai.Tenloai)</td>
                    <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Cập nhật thông tin" href="/admin/quanlysanpham/suathongtin?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/sua.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                    <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Xóa sản phẩm" onclick="return xacnhanxoa('@Html.DisplayFor(modelitem => item.Masanpham).ToString().Trim()')" href="/admin/quanlysanpham/xoasanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/xoa.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                </tr>
            }
        </table>
    </div>
    <div style="width:990px; text-align:center">
        <center>@{Html.RenderAction("Index","adminpaging", new {currentpage = "admin/quanlysanpham/index?", totalpages = ViewBag.TotalPages});}  
    </center></div>
    <div class="clear"></div>
    </div>
}
else
{
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <div class="columnleft"></div>
    <div class="columnngoai"></div>
    <div class="covercenter">
        <div class="columncenter">
            <div class="header-center">ĐĂNG NHẬP</div>
            <div class="text" style="margin: 20px 10px 20px 20px">
                <div>
                    <text> Bạn chưa đăng nhập. Vui lòng nhấn vào <a href="/admin/dangnhap?returnUrl=@Request.Url.PathAndQuery"> đây </a>để vào trang đăng nhập.</text>
                </div>
            </div>
        </div>
    </div>
}     

Trangsuc/Areas/Admin/Views/quanlysanpham/Menu.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Loaisanpham_DTO>

<ul id="danhmucquanly"><a href="/admin/quanlysanpham/index" style="text-align:center">Quản lý sản phẩm</a>
    @foreach (var item in Model)
    {
        <li><a href="/admin/quanlysanpham/danhmuc/@Html.DisplayFor(modelItem => item.Maloai)" style="padding-left:26px"><text style="font-size:12px">@Html.DisplayFor(modelItem => item.Tenloai)</text></a></li>	
    }	
    <li><a href="/admin/quanlysanpham/sanphaman" style="padding-left:26px"><text style="font-size:12px">Sản phẩm ẩn</text></a></li>	            
</ul>

Trangsuc/Areas/Admin/Views/quanlysanpham/danhmuc.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>
@if (Session["Admin"] != null)
{
    {
        Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
    }

    <div class="headercolumn">QUẢN LÝ SẢN PHẨM LOẠI <text style="text-transform: uppercase;">@Html.Raw(ViewBag.tenloai)</text></div>
    <div class="noidungright">
    <div style="width:990px">
        <div style="width:990px">
        <table>
            <tr>
                <td style="width:280px; text-align:left">
                    <div class="tieude2">
                        <a href="/admin/quanlysanpham/themsanpham" style="text-decoration:none">
                            <img src="@Url.Content("~/images/them.png")" width="10px" height="10px"/> Thêm sản phẩm mới
                        </a>
                    </div>
                </td>
                <td style="width:700px; text-align:right">
                    <div style="margin:5px; width:700px; float:right">
                        <form action="/admin/quanlysanpham/ketquatimkiemdanhmuc/@Html.Raw(ViewBag.maloai)" method="get"> 
                            Tìm kiếm cho danh mục "@Html.Raw(ViewBag.tenloai)" <input style="width:250px; height: 17px" id="coban" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="Nhập tên sản phẩm..." name="chuoitk" autocomplete="off" size="36" />
                            <input style="width:40px; height: 26px" type="submit" name="tkcoban" value="Tìm" />
                        </form>
                    </div> 
                </td>
            </tr>
        </table>
    </div>
    <div style="width:990px"><div class="tieude"><center>Danh sách sản phẩm</center></div></div>
        <table class="tablenguoidung">
                <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Chất liệu</th>
                <th>Giá (VNĐ)</th>           
                <th style="width:80px">Hình ảnh</th>
                <th>Loại</th>              
                <th colspan="2"></th>
            </tr>
                @foreach (var item in Model)
                {
                    <tr>
                    <td>@Html.DisplayFor(modelItem => item.Masanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Tensanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Chatlieu)</td>
                    @{
                    string formatgia = item.Giasanpham.ToString("c");
                    formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
                        }
                    <td>@formatgia</td>
                    <td><img src="@Url.Content("~/" + @Html.DisplayFor(modelItem => item.Hinhanh))" width="75px" height="75px"/></td>
                    <td>@Html.DisplayFor(modelItem => item.Loai.Tenloai)</td>
                    <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Cập nhật thông tin" href="/admin/quanlysanpham/suathongtin?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/sua.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                        <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Xóa sản phẩm" onclick="return xacnhanxoa('@Html.DisplayFor(modelitem => item.Masanpham).ToString().Trim()')" href="/admin/quanlysanpham/xoasanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/xoa.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                </tr>
                }
            </table>
    </div>
    <div style="width:990px">
       <center>@{Html.RenderAction("Index", "adminpaging", new { currentpage = "admin/quanlysanpham/danhmuc/" + @ViewBag.maloai +"?", totalpages = ViewBag.TotalPages });}
    </center> </div>
    <div class="clear"></div>
    </div>
}
else
{
      <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <div class="columnleft"></div>
    <div class="columnngoai"></div>
    <div class="covercenter">
        <div class="columncenter">
            <div class="header-center">ĐĂNG NHẬP</div>
            <div class="text" style="margin: 20px 10px 20px 20px">
                <div>
                    <text> Bạn chưa đăng nhập. Vui lòng nhấn vào <a href="/admin/dangnhap?returnUrl=@Request.Url.PathAndQuery"> đây </a>để vào trang đăng nhập.</text>
                </div>
            </div>
        </div>
    </div>
}     

Trangsuc/Areas/Admin/Views/quanlysanpham/ketquatimkiem.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>

@if (Session["Admin"] != null)
{

    {
        Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
    }
    <div class="headercolumn">KẾT QUẢ TÌM KIẾM SẢN PHẨM</div>
    <div class="noidungright">
    <div style="width:990px">
    <div style="width:990px">
        <table>
            <tr>
                <td style="width:480px; text-align:left">
                    <div class="tieude">Danh sách sản phẩm</div>
                </td>
                <td style="width:500px; text-align:right">
                    <div style="margin:5px; width:500px; float:right">
                        <form action="/admin/quanlysanpham/ketquatimkiem" method="get"> 
                            <input style="width:250px; height: 17px" id="coban" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="Nhập tên sản phẩm..." name="chuoitk" autocomplete="off" size="36" />
                            <input style="width:40px; height: 26px" type="submit" name="tkcoban" value="Tìm" />
                        </form>
                    </div> 
                </td>
            </tr>
        </table>
    </div>
        @if (Model.Count() < 1)
        {
            <div style="padding-left: 8px">
                <p>@Html.Raw(ViewBag.KhongTimThay) "@Html.Raw(ViewBag.Chuoi)"</p>
            </div> 
        }
        else
        {
            <table class="tablenguoidung">
                <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Chất liệu</th>
                <th>Giá (VNĐ)</th>           
                <th style="width:80px">Hình ảnh</th>
                <th>Loại</th>              
                <th colspan="2"></th>
            </tr>
                @foreach (var item in Model)
                {
                    <tr>
                    <td>@Html.DisplayFor(modelItem => item.Masanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Tensanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Chatlieu)</td>
                    @{
                    string formatgia = item.Giasanpham.ToString("c");
                    formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
                        }
                    <td>@formatgia</td>
                    <td><img src="@Url.Content("~/" + @Html.DisplayFor(modelItem => item.Hinhanh))" width="75px" height="75px"/></td>
                    <td>@Html.DisplayFor(modelItem => item.Loai.Tenloai)</td>
                    <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Cập nhật thông tin" href="/admin/quanlysanpham/suathongtin?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/sua.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                        <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Xóa sản phẩm" onclick="return xacnhanxoa('@Html.DisplayFor(modelitem => item.Masanpham).ToString().Trim()')" href="/admin/quanlysanpham/xoasanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/xoa.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                </tr>
                }
            </table>
            <div style="width:990px">
                <center>@{Html.RenderAction("Index", "adminpaging", new { currentpage = "admin/quanlysanpham/ketquatimkiem?chuoitk=" + @ViewBag.Chuoi + "&tkcoban=Tìm", totalpages = ViewBag.TotalPages });}
            </center></div>
            <div class="clear"></div>
        }
    </div>
    </div>
}
else
{
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <div class="columnleft"></div>
    <div class="columnngoai"></div>
    <div class="covercenter">
        <div class="columncenter">
            <div class="header-center">ĐĂNG NHẬP</div>
            <div class="text" style="margin: 20px 10px 20px 20px">
                <div>
                    <text> Bạn chưa đăng nhập. Xin vui lòng nhấn vào <a href="/admin/dangnhap?returnUrl=@Request.Url.PathAndQuery"> đây </a>để vào trang đăng nhập.</text>
                </div>
            </div>
        </div>
    </div>
}

Trangsuc/Areas/Admin/Views/quanlysanpham/ketquatimkiemdanhmuc.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>

@if (Session["Admin"] != null)
{

    {
        Layout = "~/Areas/Admin/Views/Shared/_Layoutadmin.cshtml";
    }
    <div class="headercolumn">KẾT QUẢ TÌM KIẾM SẢN PHẨM</div>
    <div class="noidungright">
    <div style="width:990px">
    <div style="width:990px">
        <table>
            <tr>
                <td style="width:480px; text-align:left">
                    <div class="tieude">Danh sách sản phẩm</div>
                </td>
                <td style="width:700px; text-align:right">
                    <div style="margin:5px; width:700px; float:right">
                        <form action="/admin/quanlysanpham/ketquatimkiemdanhmuc/@Html.Raw(ViewBag.maloai)" method="get"> 
                            Tìm kiếm cho danh mục "@Html.Raw(ViewBag.tenloai)" <input style="width:250px; height: 17px" id="coban" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="Nhập tên sản phẩm..." name="chuoitk" autocomplete="off" size="36" />
                            <input style="width:40px; height: 26px" type="submit" name="tkcoban" value="Tìm" />
                        </form>
                    </div> 
                </td>
            </tr>
        </table>
    </div>
        @if (Model.Count() < 1)
        {
            <div style="padding-left: 8px">
                <p>@Html.Raw(ViewBag.KhongTimThay) "@Html.Raw(ViewBag.Chuoi)" cho danh mục "@Html.Raw(ViewBag.tenloai)"</p>
            </div> 
        }
        else
        {
            <table class="tablenguoidung">
                <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Chất liệu</th>
                <th>Giá (VNĐ)</th>           
                <th style="width:80px">Hình ảnh</th>
                <th>Loại</th>              
                <th colspan="2"></th>
            </tr>
                @foreach (var item in Model)
                {
                    <tr>
                    <td>@Html.DisplayFor(modelItem => item.Masanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Tensanpham)</td>
                    <td>@Html.DisplayFor(modelItem => item.Chatlieu)</td>
                    @{
                    string formatgia = item.Giasanpham.ToString("c");
                    formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
                        }
                    <td>@formatgia</td>
                    <td><img src="@Url.Content("~/" + @Html.DisplayFor(modelItem => item.Hinhanh))" width="75px" height="75px"/></td>
                    <td>@Html.DisplayFor(modelItem => item.Loai.Tenloai)</td>
                    <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Cập nhật thông tin" href="/admin/quanlysanpham/suathongtin?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/sua.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                        <td style="padding-left:2px; padding-right: 2px; text-align:center; width:30px">
                            <a title="Xóa sản phẩm" onclick="return xacnhanxoa('@Html.DisplayFor(modelitem => item.Masanpham).ToString().Trim()')" href="/admin/quanlysanpham/xoasanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham)" style="text-decoration:none">
                                <img src="@Url.Content("~/images/xoa.png")" width="25px" height="25px"/>
                            </a>
                        </td>
                </tr>
                }
            </table>
            <div style="width:990px">
                <center>@{Html.RenderAction("Index", "adminpaging", new { currentpage = "admin/quanlysanpham/ketquatimkiem?chuoitk=" + @ViewBag.Chuoi + "&tkcoban=Tìm", totalpages = ViewBag.TotalPages });}
            </center></div>
            <div class="clear"></div>
        }
    </div>
    </div>
}
else
{
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <div class="columnleft"></div>
    <div class="columnngoai"></div>
    <div class="covercenter">
        <div class="columncenter">
            <div class="header-center">ĐĂNG NHẬP</div>
            <div class="text" style="margin: 20px 10px 20px 20px">
                <div>
                    <text> Bạn chưa đăng nhập. Vui lòng nhấn vào <a href="/admin/dangnhap?returnUrl=@Request.Url.PathAndQuery"> đây </a>để vào trang đăng nhập.</text>
                </div>
            </div>
        </div>
    </div>
}