Trangsuc/Models/sanpham.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Trangsuc.Models
{
    //Validation cho trang them san pham
    public class sanphamthem
    {
        [Required(ErrorMessage = "Bạn chưa nhập mã sản phẩm")]
        [Display(Name = "Mã sản phẩm")]
        public string masanpham { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập tên sản phẩm")]
        [Display(Name = "Tên sản phẩm")]
        public string tensanpham { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập chất liệu sản phẩm")]
        [Display(Name = "Chất liệu")]
        public string chatlieu { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập giá sản phẩm")]
        [RegularExpression(@"[0-9]+[0-9]", ErrorMessage = "Giá sản phẩm chưa hợp lệ.")]
        [Display(Name = "Giá sản phẩm")]
        public int giasanpham { get; set; }

        public string hinhanh { get; set; }
        public string maloai { get; set; }

    }
    //Validation cho trang sua san pham
    public class sanphamsua
    {
        public string masanpham { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập tên sản phẩm")]
        [Display(Name = "Tên sản phẩm")]
        public string tensanpham { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập chất liệu sản phẩm")]
        [Display(Name = "Chất liệu")]
        public string chatlieu { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập giá sản phẩm")]
        [RegularExpression(@"[0-9]+[0-9]" + ".00", ErrorMessage = "Giá sản phẩm chưa hợp lệ.")]
        [Display(Name = "Giá sản phẩm")]
        public int giasanpham { get; set; }

        
        [Display(Name = "Hình ảnh")]
        public string hinhanh { get; set; }
        public int sanphammoi { get; set; }
        public string maloai { get; set; }
    }
}

Trangsuc/Controllers/cartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trangsuc.Models;
using System.Text.RegularExpressions;
using Trangsuc.ServiceReferenceTonkho;
using System.Net.Mail;
using System.Net;
namespace Trangsuc.Controllers
{
    public class cartController : Controller
    {
        ServiceReferenceSanpham.ServiceSanphamClient db = new ServiceReferenceSanpham.ServiceSanphamClient();
        ServiceReferenceNguoidung.ServiceNguoidungClient dbnguoidung = new ServiceReferenceNguoidung.ServiceNguoidungClient();
        ServiceTonkhoClient dbtonkho = new ServiceTonkhoClient();
        public bool IsNumber(string pText)
        {
            Regex regex = new Regex(@"^[-+]?[0-9]*\.?[0-9]+$");
            return regex.IsMatch(pText);
        }
        public RedirectToRouteResult giohangthem(string masanpham, string soluong = "1")
        {
            Tonkho_DTO tk = dbtonkho.Find(masanpham);
            if (tk.Soluong > 0)
            {
                if (IsNumber(soluong))
                {
                    if (int.Parse(soluong) <= tk.Soluong)
                    {
                        if (int.Parse(soluong) < 1)
                        {
                            var item = db.Find(masanpham);
                            GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, 1);
                        }
                        else
                        {
                            var item = db.Find(masanpham);
                            GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, int.Parse(soluong));
                        }
                    }
                    else
                    {
                        var item = db.Find(masanpham);
                        GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, tk.Soluong);
                    }
                }
                else
                {
                    var item = db.Find(masanpham);
                    GetCart().AddItem(item.Masanpham, item.Tensanpham, item.Giasanpham, 1);
                }
                return RedirectToAction("Index");
            }
            else {
                return RedirectToAction("Index","Home");
            }
           
        }

        public RedirectToRouteResult giohangxoa(string masanpham)
        {
            GetCart().RemoveLine(masanpham);
            return RedirectToAction("Index");
        }

       
        public RedirectToRouteResult capnhatsoluong(string masanpham, string soluong)
        {
            Tonkho_DTO tk = dbtonkho.Find(masanpham);
            if (IsNumber(soluong))
            {            
                    if (int.Parse(soluong) <= tk.Soluong)
                    {
                        if (int.Parse(soluong) < 1)
                            GetCart().capnhatsoluong(masanpham, 1);
                        else
                            GetCart().capnhatsoluong(masanpham, int.Parse(soluong));
                    }
                    else
                    {  
                        GetCart().capnhatsoluong(masanpham, tk.Soluong); 
                    }
               
            }
            else
            {            
                    GetCart().capnhatsoluong(masanpham, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToRouteResult xoahet()
        {
            GetCart().Clear();
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult menugiohang()
        {
            return PartialView(GetCart());
        }
        //Gán session["Cart"] cho giỏ hàng
        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }

        [ChildActionOnly]
        public ActionResult footergiohang()
        {
            return PartialView();
        }


  
        public void ngaythangnam()
        {
            int nam = DateTime.Now.Year;
            List<SelectListItem> ngayList = new List<SelectListItem>();
            List<SelectListItem> thangList = new List<SelectListItem>();
            List<SelectListItem> namList = new List<SelectListItem>();
            for (int i = 1; i <= 31; i++)
            {
                string j = i.ToString();
                ngayList.Add(new SelectListItem { Text = j, Value = j });
            }
            for (int i = 1; i <= 12; i++)
            {
                string j = i.ToString();
                thangList.Add(new SelectListItem { Text = j, Value = j });
            }
            for (int i = nam; i <= nam + 1; i++)
            {
                string j = i.ToString();
                namList.Add(new SelectListItem { Text = j, Value = j });
            }
            ViewBag.ngay = ngayList;
            ViewBag.thang = thangList;
            ViewBag.nam = namList;
        }
        public ActionResult thanhtoangiohang()
        {
            if (GetCart().Lines.Count() > 0)
            {              
                    string username = (string)Session["User"];
                    var tt = GetCart().thongtinkh(username);
                        ViewBag.username = tt.Hoten;
                        ViewBag.sdt = tt.Sdt;
                        ViewBag.email = tt.Mail;
                        ViewBag.diachi = tt.Diachi;
                        ngaythangnam();
                        return View(GetCart());
            }
            return RedirectToAction("index");
        }

        //thanh toán giỏ hàng rồi gửi mail chi tiết đơn hàng cho khách hàng
        [HttpPost]
        public ActionResult thanhtoangiohang(FormCollection f)
        {

            Cart cart = GetCart();
            string name = Session["User"].ToString();
            ServiceReferenceNguoidung.Nguoidung_DTO user = new ServiceReferenceNguoidung.Nguoidung_DTO();
            user = dbnguoidung.GetNguoidungByUsername(name);

            string Email = user.Mail.Trim();
            string chuoi = " GIỎ HÀNG CỦA QUÝ KHÁCH\n";

            foreach (var item in cart.Lines)
            {
                chuoi += "Mã SP: " + item.masp + "\tTên SP: " + item.tensp + "\tSố lượng: " + item.Quantity + "\tGiá SP: " + item.giasanpham + "\n";
            }
            chuoi += "Tổng tiền:" + cart.tongtien() + "VND\n";
            chuoi += "Cám ơn quý khách đã chọn sản phẩm của công ty. Chúng tôi sẽ liên hệ sớm với quý khách.";
            MailMessage msg = new MailMessage();
            msg.From = new MailAddress("trangsucviet05@gmail.com");
            msg.To.Add(Email);
            msg.Subject = "Trangsucviet: GIỎ HÀNG CỦA QUÝ KHÁCH TẠI Trangsucviet.com.vn";
            msg.Body = chuoi;

            //cấu hình mail smtp
            #region SMTP
            SmtpClient smtp = new SmtpClient();
            smtp.Credentials = new NetworkCredential("trangsucviet05@gmail.com", "seminarnhom05");
            smtp.Port = 587;
            smtp.Host = "smtp.gmail.com";
            smtp.EnableSsl = true;
            smtp.Send(msg);
            #endregion

            int ngay = int.Parse(f["ngay"]);
            int thang = int.Parse(f["thang"]);
            int nam = int.Parse(f["nam"]);              
            DateTime ngaygiaohang = new DateTime(nam, thang, ngay);
               
            //Lưu hóa đơn hàng xuống csdl
            GetCart().save((string)Session["User"], f["diachi"], ngaygiaohang, f["sdt"]);

            //xóa danh sách sản phẩm có trong giỏ hàng
            GetCart().Clear();
            return RedirectToAction("Index", "home");
        }

     
        public ViewResult Index()
        {
            return View(GetCart());
        }
    }
}

Trangsuc/Controllers/loaisanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trangsuc.ServiceReferenceSanpham;
namespace Trangsuc.Controllers
{
    public class loaisanphamController : Controller
    {
        List<Loaisanpham_DTO> danhsachloaisanpham = new List<Loaisanpham_DTO>();
        ServiceSanphamClient db = new ServiceSanphamClient();
        //
        // GET: /loaisanpham/

        public void dsloaisanpham()
        {
            danhsachloaisanpham.Clear();
            danhsachloaisanpham = db.GetAllLoaiSp().ToList<Loaisanpham_DTO>();
        }

        //menu danh muc sản phẩm
        [ChildActionOnly]
        public ActionResult Menu()
        {
            dsloaisanpham();
            return PartialView(danhsachloaisanpham);
        }
        //list box danh muc san pham trong tim kiem nang cao
        [ChildActionOnly]
        public ActionResult Menutimkiem()
        {
            dsloaisanpham();
            return PartialView(danhsachloaisanpham);
        }

    }
}

Trangsuc/Controllers/pagingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Trangsuc.Controllers
{
    public class pagingController : Controller
    {
        //
        // GET: /paging/
        [ChildActionOnly]
        public ActionResult Index(int page=1,string currentpage=null,int totalpages=1)
        {   //dia chi trang hien tai
            ViewBag.currentpage = currentpage;
            //trang hien tai
            ViewBag.Page = page;
            //tong so trang
            ViewBag.TotalPages = totalpages;
            return PartialView();
        }

    }
}

Trangsuc/Controllers/sanphamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trangsuc.ServiceReferenceSanpham;
using System.Text.RegularExpressions;
using Trangsuc.ServiceReferenceTonkho;
namespace Trangsuc.Controllers
{ 
    public class sanphamController : Controller
    {
        public List<ServiceReferenceSanpham.Sanpham_DTO> danhsachsanpham = new List<ServiceReferenceSanpham.Sanpham_DTO>();

        ServiceTonkhoClient dbtonkho = new ServiceTonkhoClient();
        ServiceSanphamClient db = new ServiceSanphamClient();
        
        int pagesize = 6;
        public void dssanpham()
        {
            danhsachsanpham.Clear();
            danhsachsanpham = db.GetAllSp().Where(x => x.Sanphammoi == 1).ToList<ServiceReferenceSanpham.Sanpham_DTO>();
        }
        
       
        //
        // GET: /sanpham/Details/5

        public ActionResult chitietsanpham()
        {
            ServiceReferenceSanpham.Sanpham_DTO chitietsanpham = new ServiceReferenceSanpham.Sanpham_DTO();
            string masp = Request.QueryString["masp"];
            Tonkho_DTO tk = dbtonkho.Find(masp);
            ViewBag.Tonkho = tk.Soluong;
            chitietsanpham = db.Find(masp);
            if (chitietsanpham == null) return HttpNotFound();
            return View(chitietsanpham);
        }
        //san pham cùng loại hiện trong trang chi tiết sản phẩm
        [ChildActionOnly]
        public ActionResult sanphamcungloai(int page=1)
        {
            dssanpham();
            string masp = Request.QueryString["masp"];
            List<ServiceReferenceSanpham.Sanpham_DTO> sanphamcungloai = new List<ServiceReferenceSanpham.Sanpham_DTO>();
            ServiceReferenceSanpham.Sanpham_DTO sp = new ServiceReferenceSanpham.Sanpham_DTO();
            sp = danhsachsanpham.Single(x => x.Masanpham.Contains(masp));
            sanphamcungloai = db.GetSpCungLoai(sp.Loai.Maloai).Where(x=> x.Sanphammoi ==1).ToList();
            int _pagesize = 3;
            ViewBag.masp = masp;
            ViewBag.TotalPages = Math.Ceiling((double)sanphamcungloai.Count / _pagesize);
            return PartialView(sanphamcungloai.Skip((page - 1) * _pagesize).Take(_pagesize));
        }

        [ChildActionOnly]
        public ActionResult spbanchay()
        {

            List<ServiceReferenceSanpham.Sanpham_DTO> sanphambanchay = new List<ServiceReferenceSanpham.Sanpham_DTO>();
            sanphambanchay = db.GetSpBc().Where(x => x.Sanphammoi == 1).ToList();
            return PartialView(sanphambanchay);
        }
        //danh sach sản phẩm khi nhan vào danh mục sản phẩm
        public ActionResult DanhMuc(int page =1)
        {

            string maloai = Request.QueryString["maloai"];
            List<ServiceReferenceSanpham.Sanpham_DTO> sanpham = db.GetSpCungLoai(maloai).Where(x=>x.Sanphammoi ==1).ToList();
            ViewBag.tenloai = sanpham.FirstOrDefault().Tenloai;
            ViewBag.TotalPages = Math.Ceiling((double)sanpham.Count / pagesize);
            ViewBag.maloai = maloai;
            return View(sanpham.Skip((page - 1) * pagesize).Take(pagesize));

        }
        //có thể tìm kiếm theo mã hoặc tên sản phẩm
        public ActionResult TimKiem(int page=1)
        {
            dssanpham();
            string id = Request.QueryString["chuoitk"];
            id = id.ToLower();
            List<ServiceReferenceSanpham.Sanpham_DTO> kqtimkiem = new List<ServiceReferenceSanpham.Sanpham_DTO>();
            foreach (ServiceReferenceSanpham.Sanpham_DTO item in danhsachsanpham)
            {
                if (item.Tensanpham.ToLower().Contains(id) || item.Masanpham.Trim().ToLower().Contains(id))
                    kqtimkiem.Add(item);
            }
            ViewBag.Chuoi = id;
            ViewBag.KhongTimThay = "Không tìm thấy";
            ViewBag.TotalPages = Math.Ceiling((double)kqtimkiem.Count / pagesize);
            return View(kqtimkiem.Skip((page - 1) * pagesize).Take(pagesize));
        }

        //public bool IsNumber(string pText)
        //{
        //    Regex regex = new Regex(@"^[-+]?[0-9]*\.?[0-9]+$");
        //    return regex.IsMatch(pText);
        //}

        public ActionResult TimKiemNangCao(int page = 1)
        {
            dssanpham();
            string loaihang = Request.QueryString["loaihang"];
            string tensp = Request.QueryString["tensp"];
            tensp = tensp.ToLower();
            string giatu = Request.QueryString["giatu"];
            string den = Request.QueryString["den"];
            int _giatu = int.Parse(giatu);
            int _giaden = int.Parse(den);
            if (loaihang.Equals("tatca"))
            {
                loaihang = "";
            }
            if (tensp.Equals("tên sản phẩm"))
            {
                tensp = "";
            }
            List<ServiceReferenceSanpham.Sanpham_DTO> kqtimkiem = danhsachsanpham;
            if (!String.IsNullOrEmpty(loaihang))
            {
                kqtimkiem = kqtimkiem.Where(t => t.Loai.Maloai.Contains(loaihang)).ToList();
            }
            if (!String.IsNullOrEmpty(tensp))
            {
                kqtimkiem = kqtimkiem.Where(t => t.Tensanpham.ToLower().Contains(tensp)).ToList();
            }
            kqtimkiem = kqtimkiem.Where(t => (t.Giasanpham >= _giatu && t.Giasanpham <= _giaden)).ToList();
            ViewBag.KhongTimThay = "Không tìm thấy các sản phẩm thỏa điều kiện";

            //ViewBag dùng cho phân trang
            ViewBag.loaihang = loaihang;
            ViewBag.tensp = tensp;
            ViewBag.giatu = giatu;
            ViewBag.giaden = den;
            //tông số trang
            ViewBag.TotalPages = Math.Ceiling((double)kqtimkiem.Count / pagesize);
            //pagesize số sản phẩm hiện trong 1 trang
            return View(kqtimkiem.Skip((page - 1) * pagesize).Take(pagesize));
        }
        
        //khung tim kiếm cơ bản và nâng cao
        [ChildActionOnly]
        public ActionResult KhungTimKiem()
        {
            return PartialView();
        }
    }
}

Trangsuc/Views/sanpham/DanhMuc.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>
@{
    ViewBag.Title = "Danh Mục";
}

<div class="covercenter">
@{Html.RenderAction("KhungTimKiem","sanpham");}

<div class="columncenter">
    <div class="header-center">DANH MỤC SẢN PHẨM <text style="text-transform: uppercase;">@Html.Raw(ViewBag.tenloai)</text></div>
    <div class="trangsanpham">
    <div style="width:580px">
        @foreach (var item in Model)
        {
            string formatgia = item.Giasanpham.ToString("c");
            formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
            <div class="sanpham">
            <a title="Chi tiết" href="/sanpham/chitietsanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham).ToString().Trim()"><div><img src="@Url.Content("~/"+@Html.DisplayFor(modelItem => item.Hinhanh))"/></div></a>
            <div class="tensanpham"><table align="center"><tr height="40px" valign="middle"><td><b>@Html.DisplayFor(modelItem => item.Tensanpham)</b></td></tr></table></div>
            <div style="color:#FF0000"><b>Giá: @formatgia VNĐ</b></div>
            <table>
                        <tr>
                            <td align="right" style="width:100px;padding-left:7px; padding-right:5px">
                                <div class="muahang">
                                    <a title="Thêm sản phẩm vào giỏ hàng" href="/Cart/giohangthem?masanpham=@Html.DisplayFor(x => item.Masanpham)"><b>Mua hàng</b></a>
                                </div>
                            </td>
                            <td align="left" style="width:60px; padding-left:5px; padding-right:10px">
                                <div class="chitiet">
                                    <a href="/sanpham/chitietsanpham/?masp=@Html.DisplayFor(modelItem => item.Masanpham).ToString().Trim()">Chi tiết</a>
                                </div>
                            </td>
                        </tr>
                    </table>
            </div>
        }
    </div>
    </div>
    <div class="clear"></div>
    <div>
    @{Html.RenderAction("Index","paging", new {currentpage = "sanpham/DanhMuc?maloai="+@ViewBag.maloai , totalpages = ViewBag.TotalPages});} 
   </div>
</div>

</div>

Trangsuc/Views/sanpham/KhungTimKiem.cshtml
<div class="columncenter">
        <div class="header-center">TÌM KIẾM SẢN PHẨM</div>   
        <fieldset class="fieldset">
            <legend><img src="@Url.Content("~/Image/search-icon.png")" width="25" height="25" align="top" /></legend>
            <div id="wrapper">
            <form action="/sanpham/TimKiem" method="get" name="tkcoban"> 
     	        <input style="width:250px; height: 17px" id="coban" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="Nhập tên sản phẩm cần tìm..." name="chuoitk" autocomplete="off" size="36" />
     	        <input style="width:40px; height: 26px" type="submit" name="tkcoban" value="Tìm" />
	        </form>
                <a href="" id="link" onclick="return show_hide()">Tìm kiếm nâng cao</a>
            </div>
            <div id="full" style="display:none">
                <form action="/sanpham/TimKiemNangCao" method="get" name="tknangcao" onsubmit="return checktknc();">
    	             @{Html.RenderAction("Menutimkiem", "loaisanpham");}
		            <input id="tensanpham" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="tên sản phẩm" name="tensp" autocomplete="off" style="width:100px; height: 16px">
		            <input id="giatu" type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="giá từ" name="giatu" autocomplete="off" style="width:100px; height: 16px">
		            <input id="den"  type="text" onblur="if(this.value=='') this.value=this.defaultValue" onfocus="if(this.value==this.defaultValue) this.value=''" value="đến" name="den" autocomplete="off" style="width:100px; height: 16px">	
                    <input style="width:40px; height: 26px" type="submit" name="tknangcao" value="Tìm" />
                </form>
                <span id="_giatu" style="color:red"></span><br />
                <a href="" id="link" onclick="return show_hide()">Tìm kiếm cơ bản</a>
            </div>
        </fieldset>
    </div>

Trangsuc/Views/sanpham/TimKiem.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>
@{
    ViewBag.Title = "Tìm Kiếm";
}

<div class="covercenter">
<div class="columcenter"> 
 @{Html.RenderAction("KhungTimKiem", "sanpham");}
</div>

<div class="columncenter">
    <div class="header-center">KẾT QUẢ TÌM KIẾM</div>
    <div class="trangsanpham">
    <div style="width:580px">
        @if (Model.Count() < 1)
            {
            <div class="noidunggiua" style="padding:10px;">
                <div class="noidungphu">@Html.Raw(ViewBag.KhongTimThay) "@Html.Raw(ViewBag.Chuoi)"</div>
            </div>
                
            }
        else
        {
            foreach (var item in Model)
        {
            string formatgia = item.Giasanpham.ToString("c");
            formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
            <div class="sanpham">
            <a title="Chi tiết" href="/sanpham/chitietsanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham).ToString().Trim()"><div><img src="@Url.Content("~/"+@Html.DisplayFor(modelItem => item.Hinhanh))"/></div></a>
            <div class="tensanpham"><table align="center"><tr height="40px" valign="middle"><td><b>@Html.DisplayFor(modelItem => item.Tensanpham)</b></td></tr></table></div>
            <div style="color:#FF0000"><b>Giá: @formatgia VNĐ</b></div>
            <table>
                        <tr>
                            <td align="right" style="width:100px;padding-left:7px; padding-right:5px">
                                <div class="muahang">
                                    <a title="Thêm sản phẩm vào giỏ hàng" href="/Cart/giohangthem?masanpham=@Html.DisplayFor(x => item.Masanpham)"><b>Mua hàng</b></a>
                                </div>
                            </td>
                            <td align="left" style="width:60px; padding-left:5px; padding-right:10px">
                                <div class="chitiet">
                                    <a href="/sanpham/chitietsanpham/?masp=@Html.DisplayFor(modelItem => item.Masanpham).ToString().Trim()">Chi tiết</a>
                                </div>
                            </td>
                        </tr>
                    </table>
            </div>
        }
             <div>
            @{Html.RenderAction("Index", "paging", new { currentpage = "sanpham/timkiem?chuoitk=" + @ViewBag.Chuoi + "&tkcoban=Tìm", totalpages = ViewBag.TotalPages });}
            </div>
        }
    </div>
    </div>
</div>
</div>

Trangsuc/Views/sanpham/TimKiemNangCao.cshtml
@model IEnumerable<Trangsuc.ServiceReferenceSanpham.Sanpham_DTO>
@{
    ViewBag.Title = "TimKiemNangCao";
}
<div class="covercenter">
<div class="columcenter"> 
 @{Html.RenderAction("KhungTimKiem", "sanpham");}
</div>

<div class="columncenter">
    <div class="header-center">KẾT QUẢ TÌM KIẾM</div>
    @if (Model.Count() < 1)
    { 
        <div class="noidunggiua">@ViewBag.KhongTimThay</div>
    }
    else
    {
        <div class="trangsanpham">
        <div style="width:580px">
    
        @foreach (var item in Model)
        {
            string formatgia = item.Giasanpham.ToString("c");
            formatgia = formatgia.Substring(1, formatgia.LastIndexOf(".") - 1);
            <div class="sanpham">
            <a title="Chi tiết" href="/sanpham/chitietsanpham?masp=@Html.DisplayFor(modelItem => item.Masanpham).ToString().Trim()"><div><img src="@Url.Content("~/" + @Html.DisplayFor(modelItem => item.Hinhanh))"/></div></a>
            <div class="tensanpham"><table align="center"><tr height="40px" valign="middle"><td><b>@Html.DisplayFor(modelItem => item.Tensanpham)</b></td></tr></table></div>
            <div style="color:#FF0000"><b>Giá: @formatgia VNĐ</b></div>
            <table>
                        <tr>
                            <td align="right" style="width:100px;padding-left:7px; padding-right:5px">
                                <div class="muahang">
                                    <a title="Thêm sản phẩm vào giỏ hàng" href="/Cart/giohangthem?masanpham=@Html.DisplayFor(x => item.Masanpham)"><b>Mua hàng</b></a>
                                </div>
                            </td>
                            <td align="left" style="width:60px; padding-left:5px; padding-right:10px">
                                <div class="chitiet">
                                    <a href="/sanpham/chitietsanpham/?masp=@Html.DisplayFor(modelItem => item.Masanpham).ToString().Trim()">Chi tiết</a>
                                </div>
                            </td>
                        </tr>
                    </table>
            </div>
        }
            
    </div>
             <div class="clear"></div>
    </div>
        <div>
            @{Html.RenderAction("Index", "paging", new { currentpage = "sanpham/TimKiemNangCao?loaihang=" + @ViewBag.loaihang + "&tensp=" + @ViewBag.tensp + "&giatu=" + @ViewBag.giatu + "&den=" + @ViewBag.giaden + "&tknangcao=Tìm", totalpages = ViewBag.TotalPages });}
        </div>
    }
    
</div>
</div>